apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-service-deployment
  labels:
    app: spring-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-service-v1
  template:
    metadata:
      labels:
        app: spring-service-v1
    spec:
      containers:
        - name: spring-service-container
          image: omkarshetkar/spring-service:v1
          ports:
            - containerPort: 8080