apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spring-service-v1
  name: spring-service
  namespace: default
spec:
  containers:
    - image: omkarshetkar/spring-service:v1
      name: spring-service
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP