apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spring-service-rs
  labels:
    app: spring-service-rs
spec:
  # modify replicas according to your case
  replicas: 4
  selector:
    matchLabels:
      app: spring-service-v1
  template:
    metadata:
      labels:
        app: spring-service-v1
    spec:
      containers:
        - name: spring-service-container
          image: omkarshetkar/spring-service:v1