apiVersion: v1
kind: Service
metadata:
  name: mango-service
spec:
  selector:
    app: mango-app
  ports:
    - protocol: TCP
      port: 80 # Port on which service will receive the traffic
      targetPort: 8082 # Port exposed by pod onto which service delivers/receives the traffic