apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple
  labels:
    app: apple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apple-app
  template:
    metadata:
      labels:
        app: apple-app
    spec:
      containers:
        - name: apple
          image: omkarshetkar/apple:latest
          ports:
            - containerPort: 8081