apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontdesk
  labels:
    app: frontdesk-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontdesk-app
  template:
    metadata:
      labels:
        app: frontdesk-app
    spec:
      containers:
        - name: frontdesk
          image: omkarshetkar/frontdesk:latest
          ports:
            - containerPort: 8080