apiVersion: v1
kind: Service
metadata:
  name: frontdesk-service
spec:
  type: NodePort
  selector:
    app: frontdesk-app
  ports:
    - port: 80
      targetPort: 8080
      # Optional field
      # By default, Kubernetes assigns the nodeport from the range 30000-32767
      nodePort: 30007 # Here, we are explicitly assigning the nodeport